tac_model:
  model: holist
  ckpt_path: null
  distributed: true
  gpu_per_process: 0.9
  cpu_per_process: 1
  action_generator_options:
    random_tactic_probability: 0.5
    bag_of_words_similar: false
    max_theorem_parameters: 5
    asm_meson_only: false
    asm_meson_no_params_only: false
  #    num_similar_parameters:
  #      max_value: null
  #      min_value: null


  # Setting ProverOptions Proto
  path_tactics: 'experiments/HOList/config/hollight_tactics.textpb'
  path_tactics_replace: 'experiments/HOList/config/hollight_tactics_replacements.textpb'
  path_theorem_database: 'data/HOList/theorem_database_v1.1.textpb'

  model_architecture: PARAMETERS_CONDITIONED_ON_TAC

  theorem_embeddings: 'runs/HOList_embeddings/checkpoint.npy'

  data_config:
    attributes: { }
    batch_size: 16
    # todo should just be attributes of loaded model
    type: graph
    data_options:
      db: 'holist'
      filter: [ 'tokens', 'edge_index', 'edge_attr' ]
      vocab_col: vocab


  model_config:
    model_type: holist_gnn
    model_attributes:
      gnn_layers: 0 # change to 0 for BoW
      dropout: 0.2
      embedding_dim: 128
      vocab_size: 1500
