tac_model:
  model: reprover
  ckpt_path: null #runs/end_to_end/seq2seq_iteration1_best.ckpt #null

  gpu_per_process: 0.45
  cpu_per_process: 1

  config:
    model_name: kaiyuy/leandojo-lean3-tacgen-byt5-small

    ## retriever config
    ret_ckpt_path: null
    #    ret_ckpt_path: runs/retrieval/retriever_test/2024_02_02/17_56_51/checkpoints/initial.ckpt
    #    indexed_corpus_path: runs/retrieval/retriever_test/2024_02_02/17_56_51/indexed_corpus.pk
    #    eval_num_retrieved: 100

    lr: 5e-6
    warmup_steps: 200
    max_seq_len: 2300

    # generation config (sample vs beam search)
    gen_config:
      strategy: beam
      length_penalty: 0.0

    # configuration for the eval loop in training (terminates based on live proving performance)
    eval_config:
      eval_num_theorems: 200
      shuffle: false
      timeout: 600

# configuration for LoRA models
#    lora_config:
#      target_modules: ['q', 'k', 'v', 'o', 'wo', 'lm_head']
#      task_type: "SEQ_2_SEQ_LM"
#      r: 16
#      lora_alpha: 16
#      lora_dropout: 0.01
