search_model:
  search: htps
  ckpt_path: runs/goal_model/binary_model/2024_03_08/17_18_00/checkpoints/last.ckpt
  distributed: true
  gpu_per_process: 0.45
  cpu_per_process: 0.5
  exploration_constant: 1
